# 测试环境配置

# 基础URL
base_url: "https://dev-aly-us-ad-web.cdcicd.com"

# 代理配置
proxy:
  enable: false
  http: ""
  https: ""

# 认证配置
auth:
  username: "Lee"
  password: "Working@1130"

# 默认请求头
headers:
  Content-Type: "application/json"
  Accept: "application/json"
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"

# 默认请求参数
#params:
#  debug: "false"

# 超时配置
timeout:
  connect: 10
  read: 30

# 数据库配置
database:
  host: "rm-j6c68qtq22l5p8yciso.mysql.cnhk.rds.aliyuncs.com"
  port: 3306
  user: "adnet"
  password: "JGXuY8z4NedHrDJ"
  database: "adnetwork-server"
